post_install() {
  echo "Minha-Development Framework"
  echo "Enable MSM-FIRMWARE-LOADER  script"
  echo "============================================================================="
  systemctl enable msm-firmware-loader.service
  echo "============================================================================="
  systemctl enable msm-firmware-loader-unpack.service

}

post_upgrade() {
   post_install
}
